FROM golang:1.18-bullseye AS base

RUN mkdir /opt/cupcake
RUN apt update && apt install --no-install-recommends tini scons build-essential -y

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["sleep", "infinity"]

FROM base AS builder

ENV TZ="America/Sao_Paulo"
WORKDIR /opt/cupcake

ADD backend /opt/cupcake
RUN go mod download && go mod verify
RUN go build -o cupcake -a .

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["sleep", "infinity"]

FROM builder AS service
ENV TZ="America/Sao_Paulo"
WORKDIR /usr/local/bin

COPY --from=BUILDER /opt/cupcake/cupcake /usr/local/bin/cupcake
EXPOSE 3000

ENTRYPOINT ["/usr/local/bin/cupcake"]