version: "3.9"
name: "cupcake"
services:
  cupcake_backend:
    container_name: cupcake
    image: harduim/cupcake:latest
    restart: unless-stopped
    network_mode: host
    depends_on:
            - cupcake_cache
    environment:
      - TZ=America/Sao_Paulo
      - DB_HOST=$DB_HOST
      - DB_DATABASE=$DB_DATABASE
      - DB_PASSWORD=$DB_PASSWORD
      - DB_USERNAME=$DB_USERNAME
      - DB_PORT=$DB_PORT
      - ENV=$ENV
      - DEBUG=$DEBUG
      - AUTO_MIGRATE_DB=$AUTO_MIGRATE_DB
      - AUTHORITY=$AUTHORITY
      - CLIENT_ID=$CLIENT_ID
      - CLIENT_SECRET=$CLIENT_SECRET
      - REDIRECT=$REDIRECT
      - SCOPES=$SCOPES

  cupcake_cache:
    restart: unless-stopped
    image: redis:6.2.3
    container_name: cupcake_cache
    ports:
      - "127.0.0.1:6379:6379"
